name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        run: |
          # Install Docker
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update -y
          sudo apt remove containerd.io
          sudo apt install -y docker.io
      - name: Pull Jenkins image
        run: docker pull jenkins/jenkins
      - name: Run Jenkins container
        run: docker run -d -p 8080:8080 -v /srv/jenkins:/var/jenkins_home --name jenkins jenkins/jenkins
      - name: Create volumes
        run: |
          sudo mkdir -p /srv/jenkins
      - name: Wait for Jenkins to start
        run: sleep 30
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok
      - name: Configure ngrok
        run: ngrok config add-authtoken $NGROK_AUTHTOKEN
      - name: Run sshx
        run: curl -sSf https://sshx.io/get | sh -s run
