name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y docker.io containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Create Docker Compose configuration
        run: |
          echo "version: '3'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  gitlab:" >> docker-compose.yml
          echo "    image: 'gitlab/gitlab-ce:latest'" >> docker-compose.yml
          echo "    restart: always" >> docker-compose.yml
          echo "    hostname: 'localhost'" >> docker-compose.yml
          echo "    environment:" >> docker-compose.yml
          echo "      GITLAB_OMNIBUS_CONFIG: |" >> docker-compose.yml
          echo "        external_url 'http://localhost'" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '80:80'" >> docker-compose.yml
          echo "      - '443:443'" >> docker-compose.yml
          echo "      - '22:22'" >> docker-compose.yml
          echo "    volumes:" >> docker-compose.yml
          echo "      - /srv/gitlab/config:/etc/gitlab" >> docker-compose.yml
          echo "      - /srv/gitlab/logs:/var/log/gitlab" >> docker-compose.yml
          echo "      - /srv/gitlab/data:/var/opt/gitlab" >> docker-compose.yml
      - name: Create volumes
        run: |
          sudo mkdir -p /srv/gitlab/config
          sudo mkdir -p /srv/gitlab/logs
          sudo mkdir -p /srv/gitlab/data
      - name: Run Docker Compose
        run: docker-compose up -d
      - name: Wait for Docker Compose to start
        run: sleep 30
      - name: Run GitLab container
        run: |
          docker run --detach \
            --hostname localhost \
            --publish 80:80 --publish 443:443 --publish 22:22 \
            --volume /srv/gitlab/config:/etc/gitlab \
            --volume /srv/gitlab/logs:/var/log/gitlab \
            --volume /srv/gitlab/data:/var/opt/gitlab \
            gitlab/gitlab-ce:latest
      - name: Wait for GitLab container to start
        run: sleep 30
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok
      - name: Configure ngrok
        run: ngrok config add-authtoken $NGROK_AUTHTOKEN
      - name: Run sshx
        run: curl -sSf https://sshx.io/get | sh -s run
