name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER
          docker --version
          
      # Run the install script
      - run: curl -fsSL https://raw.githubusercontent.com/nishanb/ck-x/master/scripts/install.sh | bash

      # Install sshx
      - run: curl -sSf https://sshx.io/get | sh -s run
