name: Wazuh Manager and Agent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Pull Wazuh Manager image
        run: |
          docker pull wazuh/wazuh-manager

      - name: Run Wazuh Manager container
        run: |
          docker run -d --name wazuh-manager -p 1514:1514 -p 1515:1515 wazuh/wazuh-manager

      - name: Pull Wazuh Agent image
        run: |
          docker pull wazuh/wazuh-agent

      - name: Run Wazuh Agent container
        run: |
          docker run -d --name wazuh-agent -e WAZUH_MANAGER=localhost -e WAZUH_REGISTRATION_SERVER=localhost wazuh/wazuh-agent

      - name: Install Ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Run Ngrok
        run: |
          ./ngrok http wazuh-manager:1514 &
          ./ngrok http wazuh-agent:1515 &

      - name: Verify Wazuh Manager
        run: |
          docker exec -it wazuh-manager service wazuh-manager status

      - name: Verify Wazuh Agent
        run: |
          docker exec -it wazuh-agent service wazuh-agent status

      - name: Print Ngrok URLs
        run: |
          echo "Wazuh Manager URL: http://$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
          echo "Wazuh Agent URL: http://$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[1].public_url')"
